---
title: "Rebecca N Assignment 10"
output: html_notebook
author: "Rebecca Neal"
Date: "19 April"
Version: "1.0"
---

This is a notebook for Assignment 10 focused on data wrangling

### Load in packages
```{r}
library(tidyverse)
library(ggplot2)
```

### Q1 Load data
```{r}
JE <- read_csv("Johnson Elementary ELA Project.csv", skip=4,
               col_names= c("Room", "Student ID", 
               "TA", "Q1", "Q2","Q3", "Q4"))
```

### Q1 Seperate Tardies and Absences
```{r}
JE <- JE %>%
  separate(TA, into = c("Tardies", "Absences"), sep = ";") 
  
```

### Q1 Clean Tardies & Absences
```{r}
JE$Tardies <- parse_integer(JE$Tardies)
JE$Absences <- parse_integer(JE$Absences)
```

### Q1 Fill in room data, drop header lines, and make Quarter and Scores variable
```{r}
JE <- JE %>%
  fill(Room) %>%
  drop_na(`Student ID`) %>%
  gather(Q1, Q2, Q3, Q4,
         key = "Quarter",
         value = "Scores")
  
```

### Q2 Write script for summary tardies and absences by room number
```{r}
JE %>%
  group_by(Room) %>%
  summarize(Absence_Mean = mean(Absences, na.rm=TRUE),
            Absence_SD = sd(Absences, na.rm = TRUE),
            Absence_Median = median(Absences, na.rm = TRUE),
            Tardy_Mean = mean(Tardies, na.rm = TRUE),
            Tardy_SD = sd(Tardies, na.rm = TRUE),
            Tardy_Median = median(Tardies, na.rm = TRUE))
            
```

### Q3 Frequency of missing data points for each quarter by room
```{r}
Missing_Data <- JE %>%
  group_by(Room) %>%
  count(sum(is.na(`2nd Quarter`))) 

```










